### ISSUE TITLE
CONTACTページ実装

### ISSUE THREAD

**Issue by ykllog** [ykllog/tenkue-r007#5]
CONTACTページ実装＠おーもとさん

**Comment by Taka-hyt** [comment]
@ohmoto-2020 
SPの際の入力フォームのフォントサイズが少し大きいようですので修正お願いします。
PCとTabletは問題内容です。
よろしくお願いします。
<img width="357" alt="スクリーンショット 2020-11-09 21 42 59" src="https://user-images.githubusercontent.com/53964838/98542696-a0232100-22d4-11eb-85bf-2fde382194c0.png">
